/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Man.glb -T 
Files: Man.glb [493.2KB] > F:\My Documents\Sites games\move-match\public\models\Man-transformed.glb [157.71KB] (68%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { LoopOnce, LoopRepeat } from 'three'
import { SkeletonUtils } from 'three-stdlib'

const IDLE_ACTION = 'HumanArmature|Man_Idle'
const MAX_ACTION_DURATION_MS = 500
const ACTION_FADE_DURATION = 0.1

export const ModelMan = React.memo(function ModelMan({ action, moveIndex = 0, scale, ...props }) {
  const group = React.useRef()
  const timeoutRef = React.useRef(null)
  const activeActionRef = React.useRef(null)
  const activeActionNameRef = React.useRef(null)
  const lastQueuedMoveIndexRef = React.useRef(0)
  const { scene, animations } = useGLTF('models/Man-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  const [pendingActions, setPendingActions] = React.useState([])
  const [currentAction, setCurrentAction] = React.useState(null)
  const [renderScale, setRenderScale] = React.useState(scale)

  const actionKeys = React.useMemo(() => Object.keys(actions || {}), [actions])

  const clearScheduledTransition = React.useCallback(() => {
    if (timeoutRef.current == null) return

    window.clearTimeout(timeoutRef.current)
    timeoutRef.current = null
  }, [])

  const resolveActionName = React.useCallback(requestedAction => {
    if (!requestedAction) return null

    if (actions[requestedAction]) return requestedAction

    const normalizedRequestedAction = requestedAction.toLowerCase()

    return (
      actionKeys.find(name => name.toLowerCase() === normalizedRequestedAction) ||
      actionKeys.find(name => name.toLowerCase().includes(normalizedRequestedAction)) ||
      null
    )
  }, [actionKeys, actions])

  const playAction = React.useCallback((requestedAction, { loopOnce = false } = {}) => {
    const actionName = resolveActionName(requestedAction)
    if (!actionName) return null

    const targetAction = actions[actionName]
    if (!targetAction) return null

    clearScheduledTransition()

    const previousAction = activeActionRef.current
    if (previousAction && previousAction !== targetAction) {
      previousAction.fadeOut(ACTION_FADE_DURATION)
    }

    targetAction.enabled = true
    targetAction.reset()
    targetAction.time = 0
    targetAction.setEffectiveTimeScale(1)
    targetAction.setEffectiveWeight(1)
    targetAction.clampWhenFinished = loopOnce
    targetAction.setLoop(loopOnce ? LoopOnce : LoopRepeat, loopOnce ? 1 : Number.POSITIVE_INFINITY)
    targetAction.fadeIn(ACTION_FADE_DURATION).play()

    activeActionRef.current = targetAction
    activeActionNameRef.current = actionName

    return targetAction
  }, [actions, clearScheduledTransition, resolveActionName])

  const idleActionName = React.useMemo(() => resolveActionName(IDLE_ACTION), [resolveActionName])

  React.useEffect(() => {
    if (!action || action === IDLE_ACTION || moveIndex <= 0) return
    if (lastQueuedMoveIndexRef.current === moveIndex) return

    lastQueuedMoveIndexRef.current = moveIndex
    setPendingActions(queue => [...queue, { action, moveIndex, scale }])
  }, [action, moveIndex, scale])

  React.useEffect(() => {
    if (currentAction || pendingActions.length > 0) return

    setRenderScale(scale)
  }, [currentAction, pendingActions.length, scale])

  React.useEffect(() => {
    if (!actionKeys.length || currentAction) return

    if (pendingActions.length > 0) {
      setCurrentAction(pendingActions[0])
      setPendingActions(queue => queue.slice(1))
      return
    }

    if (idleActionName && activeActionNameRef.current !== idleActionName) {
      playAction(idleActionName)
    }
  }, [actionKeys.length, currentAction, idleActionName, pendingActions, playAction])

  React.useEffect(() => {
    if (!currentAction || !actionKeys.length) return

    setRenderScale(currentAction.scale)

    const targetAction = playAction(currentAction.action, { loopOnce: true })
    if (!targetAction) {
      setCurrentAction(null)
      return
    }

    const clipDurationMs = (targetAction.getClip()?.duration ?? MAX_ACTION_DURATION_MS / 1000) * 1000

    timeoutRef.current = window.setTimeout(() => {
      targetAction.fadeOut(ACTION_FADE_DURATION)
      timeoutRef.current = null
      setCurrentAction(null)
    }, Math.min(clipDurationMs, MAX_ACTION_DURATION_MS))

    return () => {
      clearScheduledTransition()
    }
  }, [actionKeys.length, clearScheduledTransition, currentAction, playAction])

  React.useEffect(() => {
    return () => {
      clearScheduledTransition()
      Object.values(actions || {}).forEach(animationAction => {
        animationAction?.stop?.()
      })
    }
  }, [actions, clearScheduledTransition])

  return (
    <group ref={group} {...props} dispose={null} scale={renderScale}>
      <group name="Root_Scene">
        <primitive object={nodes.Bone} />
        <group name="BaseHuman" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh name="BaseHuman_1" geometry={nodes.BaseHuman_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.BaseHuman_1.skeleton} />
          <skinnedMesh name="BaseHuman_2" geometry={nodes.BaseHuman_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.BaseHuman_2.skeleton} />
          <skinnedMesh name="BaseHuman_3" geometry={nodes.BaseHuman_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.BaseHuman_3.skeleton} />
          <skinnedMesh name="BaseHuman_4" geometry={nodes.BaseHuman_4.geometry} material={materials.PaletteMaterial001} skeleton={nodes.BaseHuman_4.skeleton} />
          <skinnedMesh name="BaseHuman_5" geometry={nodes.BaseHuman_5.geometry} material={materials.PaletteMaterial001} skeleton={nodes.BaseHuman_5.skeleton} />
          <skinnedMesh name="BaseHuman_6" geometry={nodes.BaseHuman_6.geometry} material={materials.PaletteMaterial001} skeleton={nodes.BaseHuman_6.skeleton} />
        </group>
      </group>
    </group>
  )
})

useGLTF.preload('models/Man-transformed.glb')
