/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 MinnieMouse.glb -T 
Files: MinnieMouse.glb [767.96KB] > F:\My Documents\Sites games\move-match\public\models\MinnieMouse-transformed.glb [122.28KB] (84%)
Author: ThisIsntAPerson (https://sketchfab.com/ThisIsntAPerson)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/minnie-mouse-ae65c1698fdd4eccaaf4bb8bc8ef31fb
Title: Minnie Mouse
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function ModelMinnieMouse(props) {
  const { scene } = useGLTF('models/MinnieMouse-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null} scale={300}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.hr_minnie_mouse_mat} skeleton={nodes.Object_6.skeleton} scale={0.01} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.hr_minnie_mouse_mat} skeleton={nodes.Object_8.skeleton} scale={0.01} />
    </group>
  )
}

useGLTF.preload('models/MinnieMouse-transformed.glb')
