/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function ManWithNewAnimations({ action, ...props }) {

  const group = useRef()
  const { nodes, materials, animations } = useGLTF('models/UAL1_Standard.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
        // console.log(`Playing actions`, actions)

        if (action && actions[action]) {            
            actions[action].reset()?.fadeIn(0.2).play()
            return () => actions[action]?.fadeOut(0.2)
        }
    }, [action, actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <group name="Mannequin">
            <skinnedMesh
              name="Mannequin_1"
              geometry={nodes.Mannequin_1.geometry}
              material={materials.M_Main}
              skeleton={nodes.Mannequin_1.skeleton}
            />
            <skinnedMesh
              name="Mannequin_2"
              geometry={nodes.Mannequin_2.geometry}
              material={materials.M_Joints}
              skeleton={nodes.Mannequin_2.skeleton}
            />
          </group>
          <primitive object={nodes.root} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/UAL1_Standard.glb')
